### ISSUE TITLE
app keep crashing

### ISSUE THREAD

**Issue by irslanT** [dhkatz/t5de#9]
hello when i try to open this software it crashes 
![report](https://user-images.githubusercontent.com/129612834/229302729-58d46e0c-684a-4f9f-b307-c920751c71ed.png)

**Comment by irslanT** [comment]
any solution?

**Comment by dhkatz** [comment]
Please try the latest version if possible. It appears IMVU has made a lot of fixes for crashing since 544.16

**Comment by dhkatz** [comment]
Please update to 1.1.0 https://github.com/dhkatz/t5de/releases/tag/1.1.0
